# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d04b6cc5c819aac7dd9a8ce3233369f547f6a2b17701fec5b5a96552166bc8c711e14c5babc048bec3ebf8050376607fd867269e020c8e719defaab0e5f2149d

test:
  secret_key_base: e5179dc99e106e9907e903a5118bad44e2a804418387328e039f54a45a3a742b9efca87b0fc3ba004c0d3f33207868957e0f8866d0b302fcd49cc3f291e2ddd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
